--- #YAML:1.0
name:               Redis-Object
version:            v0.1.2
abstract:           Redis object oriented access
author:
    - Ulrich Kautz <uk@fortrabbit.de>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Serializer:  0
    Moose:             2.0.0
    Redis:             0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
